/**
 * @fileoverview Styles for the Products screen and its sub-components.
 * Contains all StyleSheet definitions extracted from products.tsx.
 * Organized by component area: steps, main, detail, variant, subtabs, step2, step3, grid, attrMgmt.
 */

import { StyleSheet } from 'react-native';

export const stepStyles = StyleSheet.create({
  container: {
    flexDirection: 'row', alignItems: 'center',
    justifyContent: 'center', paddingHorizontal: 16, paddingVertical: 12, gap: 0,
  },
  stepRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  stepCircle: {
    width: 24, height: 24, borderRadius: 12, borderWidth: 1.5,
    alignItems: 'center' as const, justifyContent: 'center' as const,
  },
  stepNumber: { fontSize: 11, fontWeight: '700' as const },
  stepLabel: { fontSize: 11, fontWeight: '600' as const },
  stepLine: { width: 24, height: 2, borderRadius: 1, marginHorizontal: 4 },
  sectionTitle: { fontSize: 16, fontWeight: '700' as const },
  sectionHint: { fontSize: 13, lineHeight: 18 },
  attrCard: { borderWidth: 1, borderRadius: 10, overflow: 'hidden' as const },
  attrHeader: {
    flexDirection: 'row', alignItems: 'center',
    gap: 10, padding: 14,
  },
  checkbox: {
    width: 20, height: 20, borderRadius: 4, borderWidth: 1.5,
    alignItems: 'center' as const, justifyContent: 'center' as const,
  },
  attrName: { fontSize: 14, fontWeight: '600' as const, flex: 1 },
  attrCount: { fontSize: 12 },
  attrValues: {
    flexDirection: 'row', flexWrap: 'wrap',
    gap: 6, paddingHorizontal: 14, paddingBottom: 14,
  },
  valueChip: {
    flexDirection: 'row', alignItems: 'center',
    gap: 4, paddingHorizontal: 10, paddingVertical: 6,
    borderRadius: 16, borderWidth: 1,
  },
  valueChipText: { fontSize: 12, fontWeight: '500' as const },
  emptyAttrs: { padding: 20, borderRadius: 10, alignItems: 'center' as const },
  emptyText: { fontSize: 13, textAlign: 'center' as const },
  bulkRow: {
    flexDirection: 'row', alignItems: 'center',
    gap: 8, padding: 10, borderRadius: 10, borderWidth: 1,
  },
  bulkLabel: { fontSize: 11, fontWeight: '600' as const },
  bulkInput: {
    borderWidth: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 6, fontSize: 12,
  },
  bulkBtn: {
    width: 32, height: 32, borderRadius: 8,
    alignItems: 'center' as const, justifyContent: 'center' as const,
  },
  draftCard: { borderWidth: 1, borderRadius: 10, padding: 10, gap: 8 },
  draftHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  draftHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 10 },
  draftHeaderText: { fontSize: 11, fontWeight: '600' as const, textTransform: 'uppercase' as const },
  draftAttrLabel: { flex: 1, fontSize: 13, fontWeight: '600' as const },
  draftFields: { flexDirection: 'row', gap: 6, flexWrap: 'wrap' },
  draftInput: {
    borderWidth: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 6, fontSize: 12, minWidth: 70,
  },
  formFooter: {
    flexDirection: 'row', justifyContent: 'space-between',
    alignItems: 'center', padding: 16, borderTopWidth: 1, gap: 10,
  },
  cancelBtn: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8, borderWidth: 1, gap: 4,
  },
  cancelBtnText: { fontSize: 13, fontWeight: '600' as const },
  nextBtn: {
    flexDirection: 'row', alignItems: 'center',
    paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8, gap: 6,
  },
  nextBtnText: { color: '#FFF', fontSize: 13, fontWeight: '600' as const },
});

export const styles = StyleSheet.create({
  container: { flex: 1 },
  body: { flex: 1 },
  bodyContent: { padding: 20, gap: 12 },
  filterBar: { flexDirection: 'row', gap: 8, alignItems: 'center', flexWrap: 'wrap' },
  searchBar: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8, gap: 8 },
  searchInput: { flex: 1, fontSize: 13, outlineStyle: 'none' as never },
  archiveToggle: { width: 36, height: 36, alignItems: 'center' as const, justifyContent: 'center' as const, borderRadius: 8, borderWidth: 1 },
  sortDropdownBtn: { width: 36, height: 36, alignItems: 'center' as const, justifyContent: 'center' as const, borderRadius: 8, borderWidth: 1 },
  sortDropdownMenu: { position: 'absolute' as const, top: 40, right: 0, borderWidth: 1, borderRadius: 10, minWidth: 130, zIndex: 100, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 8, elevation: 6 },
  sortDropdownItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingVertical: 10 },
  sortDropdownItemText: { fontSize: 13, fontWeight: '500' as const },
  listThumb: { width: 36, height: 36, borderRadius: 6 },
  listThumbPlaceholder: { width: 36, height: 36, borderRadius: 6, alignItems: 'center' as const, justifyContent: 'center' as const },
  tableCard: { borderWidth: 1, borderRadius: 14, overflow: 'hidden' as const, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.08, shadowRadius: 12, elevation: 4 },
  tableRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 14, borderBottomWidth: 1 },
  cellText: { fontSize: 13 },
  cellBold: { fontSize: 13, fontWeight: '600' as const },
  productName: { fontSize: 14, fontWeight: '600' as const },
  stockBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 12 },
  stockText: { fontSize: 12, fontWeight: '600' as const },
  mobileRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: 1 },
  mobileCell: { fontSize: 12 },
  iconBtn: { padding: 6, borderRadius: 6 },
  addBtn: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderRadius: 8, gap: 6 },
  addBtnText: { color: '#FFF', fontSize: 14, fontWeight: '600' as const },
  emptyState: { alignItems: 'center' as const, paddingVertical: 48, gap: 12 },
  emptyIconCircle: { width: 72, height: 72, borderRadius: 36, alignItems: 'center' as const, justifyContent: 'center' as const, marginBottom: 4 },
  emptyTitle: { fontSize: 16, fontWeight: '600' as const, textAlign: 'center' as const },
  emptySubtitle: { fontSize: 13, textAlign: 'center' as const, lineHeight: 18 },
  errorBanner: { padding: 12, borderRadius: 8 },
  errorText: { fontSize: 13, fontWeight: '500' as const },
  formRow: { flexDirection: 'row', gap: 12 },
  formCol: { flex: 1 },
  marginInfo: { padding: 10, borderRadius: 8 },
  marginInfoText: { fontSize: 13, fontWeight: '600' as const, textAlign: 'center' as const },
  sortRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingBottom: 4 },
  sortChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, borderWidth: 1 },
  sortChipText: { fontSize: 11, fontWeight: '500' as const },
  columnHeaderBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 10 },
  columnHeaderBarMobile: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8 },
  colHeaderText: { fontSize: 10, fontWeight: '700' as const, color: '#6B7280', letterSpacing: 0.5 },
  variantBadge: { flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 6, paddingVertical: 2, borderRadius: 10 },
  variantBadgeText: { fontSize: 10, fontWeight: '700' as const },
  categoryHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 20, paddingVertical: 10, borderRadius: 8, marginBottom: 4 },
  categoryHeaderText: { fontSize: 14, fontWeight: '700' as const },
  categoryHeaderCount: { fontSize: 12, fontWeight: '500' as const },
  photoUrlInput: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14 },
  photoPreviewContainer: { alignItems: 'flex-start' as const, marginTop: 4 },
  photoPreview: { width: 80, height: 80, borderRadius: 10 },
  typeBadgeInline: { paddingHorizontal: 6, paddingVertical: 2, borderRadius: 6 },
  typeBadgeInlineText: { fontSize: 9, fontWeight: '700' as const, textTransform: 'uppercase' as const },
  dupWarning: {
    flexDirection: 'row', alignItems: 'flex-start' as const,
    gap: 10, padding: 12, borderRadius: 10, borderWidth: 1,
  },
  dupWarningText: { fontSize: 12, color: '#92400E', lineHeight: 18 },
  dupWarningLink: { marginTop: 6 },
  dupWarningLinkText: { fontSize: 12, fontWeight: '600' as const, color: '#1D4ED8', textDecorationLine: 'underline' as const },
  headerBtn: { width: 36, height: 36, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1,},
  smBtn: { width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1,},
});

export const detailStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center' as const, alignItems: 'center' as const },
  modal: { borderRadius: 16, maxHeight: '90%' as unknown as number, shadowColor: '#000', shadowOffset: { width: 0, height: 8 }, shadowOpacity: 0.18, shadowRadius: 24, elevation: 12, overflow: 'hidden' as const },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, gap: 12 },
  backBtn: { width: 32, height: 32, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const },
  headerCenter: { flex: 1 },
  headerTitle: { fontSize: 17, fontWeight: '700' as const, letterSpacing: -0.2 },
  headerSubtitle: { fontSize: 12, marginTop: 2 },
  editBtn: { width: 32, height: 32, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const },
  deleteBtn: { width: 32, height: 32, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const },
  body: { flex: 1 },
  bodyContent: { padding: 20, gap: 16 },
  productImage: { width: '100%' as unknown as number, height: 180, borderRadius: 12 },
  description: { fontSize: 14, lineHeight: 20 },
  priceCard: { borderWidth: 1, borderRadius: 12, padding: 16 },
  priceRow: { flexDirection: 'row', gap: 12 },
  priceLabel: { fontSize: 11, fontWeight: '600' as const, textTransform: 'uppercase' as const, letterSpacing: 0.3, marginBottom: 4 },
  priceValue: { fontSize: 16, fontWeight: '700' as const },
  infoSection: { borderWidth: 1, borderRadius: 12, padding: 16, gap: 12 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  infoLabel: { fontSize: 13 },
  infoValue: { fontSize: 13, fontWeight: '600' as const },
  stockBadge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 12 },
  stockText: { fontSize: 13, fontWeight: '700' as const },
  variantsSection: { borderWidth: 1, borderRadius: 12, overflow: 'hidden' as const },
  variantsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 16 },
  variantsTitle: { fontSize: 15, fontWeight: '700' as const },
  variantCountBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 10 },
  variantCountText: { fontSize: 11, fontWeight: '700' as const },
  addVariantBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 12, paddingVertical: 6, borderRadius: 8 },
  addVariantText: { fontSize: 12, fontWeight: '600' as const },
  addVariantBtnHeader: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8 },
  addVariantTextHeader: { fontSize: 11, fontWeight: '600' as const },
  emptyVariants: { alignItems: 'center' as const, paddingVertical: 24, paddingHorizontal: 16, gap: 6 },
  emptyVariantsText: { fontSize: 14, fontWeight: '500' as const },
  emptyVariantsHint: { fontSize: 12, textAlign: 'center' as const },
  variantTableHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 8 },
  variantHeaderCell: { fontSize: 10, fontWeight: '700' as const, color: '#6B7280', letterSpacing: 0.4 },
  variantRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1, gap: 8 },
  variantAttrText: { fontSize: 13, fontWeight: '600' as const },
});

export const variantStyles = StyleSheet.create({
  sectionLabel: { fontSize: 13, fontWeight: '600' as const, marginBottom: -8 },
  attrRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-start' as const },
  addAttrBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderStyle: 'dashed' as const,
  },
  addAttrText: { fontSize: 12, fontWeight: '600' as const },
});

export const subTabStyles = StyleSheet.create({
  bar: {
    flexDirection: 'row', borderBottomWidth: 1,
    paddingHorizontal: 20, gap: 0, minHeight: 40,
    alignItems: 'center', justifyContent: 'space-between',
  },
  tabsRow: { flexDirection: 'row', alignItems: 'center' },
  actionsRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  tab: {
    flexDirection: 'row', alignItems: 'center',
    gap: 6, paddingVertical: 10, paddingHorizontal: 14,
    borderBottomWidth: 2, borderBottomColor: 'transparent',
  },
  tabText: { fontSize: 13, fontWeight: '600' as const },
  badge: { paddingHorizontal: 6, paddingVertical: 1, borderRadius: 8 },
  badgeText: { fontSize: 11, fontWeight: '700' as const },
});

export const step2Styles = StyleSheet.create({
  inlineAddRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  inlineInput: { borderWidth: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, fontSize: 12, width: 100 },
  inlineAddBtn: { width: 24, height: 24, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const },
  addValueBtn: {
    flexDirection: 'row', alignItems: 'center', gap: 3,
    paddingHorizontal: 8, paddingVertical: 5, borderRadius: 14,
    borderWidth: 1.5, borderStyle: 'dashed' as const,
  },
  addValueBtnText: { fontSize: 11, fontWeight: '600' as const },
  addAttrBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 6, paddingVertical: 12, borderRadius: 10, borderWidth: 1.5, borderStyle: 'dashed' as const,
  },
  addAttrBtnText: { fontSize: 13, fontWeight: '600' as const },
  newAttrCard: { borderWidth: 1.5, borderRadius: 10, padding: 16, gap: 12 },
  newAttrTitle: { fontSize: 14, fontWeight: '700' as const },
  newAttrInput: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9, fontSize: 13 },
  newAttrActions: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' as const },
  newAttrCancel: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1 },
  newAttrCancelText: { fontSize: 13, fontWeight: '600' as const },
  newAttrSubmit: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8 },
  newAttrSubmitText: { color: '#FFF', fontSize: 13, fontWeight: '600' as const },
});

export const step3Styles = StyleSheet.create({
  simpleCard: { borderWidth: 1, borderRadius: 12, padding: 16, gap: 12 },
});

export const gridStyles = StyleSheet.create({
  viewToggle: { flexDirection: 'row', borderRadius: 8, overflow: 'hidden' as const },
  viewToggleBtn: { width: 36, height: 36, alignItems: 'center' as const, justifyContent: 'center' as const, borderRadius: 8 },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 20 },
  productTile: { borderWidth: 1, borderRadius: 14, overflow: 'hidden' as const, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.06, shadowRadius: 8, elevation: 3 },
  tileImage: { width: '100%' as unknown as number, height: 80 },
  tilePlaceholder: { width: '100%' as unknown as number, height: 60, alignItems: 'center' as const, justifyContent: 'center' as const },
  tileBody: { padding: 8, gap: 3 },
  tileCatBadge: { paddingHorizontal: 5, paddingVertical: 1, borderRadius: 4, alignSelf: 'flex-start' as const },
  tileCatBadgeText: { fontSize: 9, fontWeight: '700' as const, textTransform: 'uppercase' as const, letterSpacing: 0.3 },
  tileName: { fontSize: 12, fontWeight: '600' as const, lineHeight: 16 },
  tilePrice: { fontSize: 13, fontWeight: '700' as const, marginTop: 2 },
});

export const attrMgmtStyles = StyleSheet.create({
  input: { borderWidth: 1, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 10, fontSize: 14 },
  empty: { alignItems: 'center' as const, paddingVertical: 40, gap: 8 },
  emptyText: { fontSize: 14, fontWeight: '500' as const },
  attrCard: { borderWidth: 1, borderRadius: 10, padding: 14, gap: 10 },
  attrHeader: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  attrName: { fontSize: 15, fontWeight: '600' as const, flex: 1 },
  attrCount: { fontSize: 12 },
  editBtn: { padding: 6, borderRadius: 6 },
  deleteBtn: { padding: 6, borderRadius: 6 },
  renameRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 6 },
  renameInput: { flex: 1, borderWidth: 1.5, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6, fontSize: 14, fontWeight: '600' as const },
  renameConfirmBtn: { width: 26, height: 26, borderRadius: 13, alignItems: 'center' as const, justifyContent: 'center' as const },
  valuesRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    paddingVertical: 4,
  },
  valueChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    paddingHorizontal: 6,
    paddingVertical: 5,
    borderRadius: 14,
    borderWidth: 1,
  },
  valueText: { fontSize: 12, fontWeight: '500' as const, paddingHorizontal: 2 },
  reorderBtn: {
    padding: 3,
    borderRadius: 4,
  },
  removeBtn: {
    padding: 3,
    marginLeft: 2,
  },
  addValueBtnSmall: { width: 28, height: 28, borderRadius: 14, borderWidth: 1.5, borderStyle: 'dashed' as const, alignItems: 'center' as const, justifyContent: 'center' as const },
  inlineAddRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  inlineInput: { borderWidth: 1, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, fontSize: 12, width: 100 },
  inlineAddBtnSmall: { width: 24, height: 24, borderRadius: 12, alignItems: 'center' as const, justifyContent: 'center' as const },
  addGroupBtn: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
    gap: 8, paddingVertical: 14, borderRadius: 10, borderWidth: 1.5, borderStyle: 'dashed' as const,
  },
  addGroupBtnText: { fontSize: 14, fontWeight: '600' as const },
  newGroupCard: { borderWidth: 1.5, borderRadius: 12, padding: 16, gap: 12 },
  newGroupTitle: { fontSize: 15, fontWeight: '700' as const },
  newGroupActions: { flexDirection: 'row', gap: 8, justifyContent: 'flex-end' as const, marginTop: 4 },
  newGroupCancelBtn: { paddingHorizontal: 16, paddingVertical: 9, borderRadius: 8, borderWidth: 1 },
  newGroupCancelText: { fontSize: 13, fontWeight: '600' as const },
  newGroupSubmitBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 16, paddingVertical: 9, borderRadius: 8 },
  newGroupSubmitText: { color: '#FFF', fontSize: 13, fontWeight: '600' as const },
});
