const POSTAL_CODE_MAP: Record<string, { city: string; country: string }> = {
  '75001': { city: 'Paris 1er', country: 'France' },
  '75002': { city: 'Paris 2e', country: 'France' },
  '75003': { city: 'Paris 3e', country: 'France' },
  '75004': { city: 'Paris 4e', country: 'France' },
  '75005': { city: 'Paris 5e', country: 'France' },
  '75006': { city: 'Paris 6e', country: 'France' },
  '75007': { city: 'Paris 7e', country: 'France' },
  '75008': { city: 'Paris 8e', country: 'France' },
  '75009': { city: 'Paris 9e', country: 'France' },
  '75010': { city: 'Paris 10e', country: 'France' },
  '75011': { city: 'Paris 11e', country: 'France' },
  '75012': { city: 'Paris 12e', country: 'France' },
  '75013': { city: 'Paris 13e', country: 'France' },
  '75014': { city: 'Paris 14e', country: 'France' },
  '75015': { city: 'Paris 15e', country: 'France' },
  '75016': { city: 'Paris 16e', country: 'France' },
  '75017': { city: 'Paris 17e', country: 'France' },
  '75018': { city: 'Paris 18e', country: 'France' },
  '75019': { city: 'Paris 19e', country: 'France' },
  '75020': { city: 'Paris 20e', country: 'France' },
  '13001': { city: 'Marseille 1er', country: 'France' },
  '13002': { city: 'Marseille 2e', country: 'France' },
  '13003': { city: 'Marseille 3e', country: 'France' },
  '13004': { city: 'Marseille 4e', country: 'France' },
  '13005': { city: 'Marseille 5e', country: 'France' },
  '13006': { city: 'Marseille 6e', country: 'France' },
  '13007': { city: 'Marseille 7e', country: 'France' },
  '13008': { city: 'Marseille 8e', country: 'France' },
  '69001': { city: 'Lyon 1er', country: 'France' },
  '69002': { city: 'Lyon 2e', country: 'France' },
  '69003': { city: 'Lyon 3e', country: 'France' },
  '69004': { city: 'Lyon 4e', country: 'France' },
  '69005': { city: 'Lyon 5e', country: 'France' },
  '69006': { city: 'Lyon 6e', country: 'France' },
  '69007': { city: 'Lyon 7e', country: 'France' },
  '69008': { city: 'Lyon 8e', country: 'France' },
  '69009': { city: 'Lyon 9e', country: 'France' },
  '31000': { city: 'Toulouse', country: 'France' },
  '31100': { city: 'Toulouse', country: 'France' },
  '31200': { city: 'Toulouse', country: 'France' },
  '31300': { city: 'Toulouse', country: 'France' },
  '31400': { city: 'Toulouse', country: 'France' },
  '31500': { city: 'Toulouse', country: 'France' },
  '06000': { city: 'Nice', country: 'France' },
  '06100': { city: 'Nice', country: 'France' },
  '06200': { city: 'Nice', country: 'France' },
  '06300': { city: 'Nice', country: 'France' },
  '44000': { city: 'Nantes', country: 'France' },
  '44100': { city: 'Nantes', country: 'France' },
  '44200': { city: 'Nantes', country: 'France' },
  '44300': { city: 'Nantes', country: 'France' },
  '34000': { city: 'Montpellier', country: 'France' },
  '34070': { city: 'Montpellier', country: 'France' },
  '34080': { city: 'Montpellier', country: 'France' },
  '34090': { city: 'Montpellier', country: 'France' },
  '67000': { city: 'Strasbourg', country: 'France' },
  '67100': { city: 'Strasbourg', country: 'France' },
  '67200': { city: 'Strasbourg', country: 'France' },
  '33000': { city: 'Bordeaux', country: 'France' },
  '33100': { city: 'Bordeaux', country: 'France' },
  '33200': { city: 'Bordeaux', country: 'France' },
  '33300': { city: 'Bordeaux', country: 'France' },
  '59000': { city: 'Lille', country: 'France' },
  '59100': { city: 'Roubaix', country: 'France' },
  '59200': { city: 'Tourcoing', country: 'France' },
  '59300': { city: 'Valenciennes', country: 'France' },
  '35000': { city: 'Rennes', country: 'France' },
  '35100': { city: 'Rennes', country: 'France' },
  '35200': { city: 'Rennes', country: 'France' },
  '51100': { city: 'Reims', country: 'France' },
  '76000': { city: 'Rouen', country: 'France' },
  '76100': { city: 'Rouen', country: 'France' },
  '42000': { city: 'Saint-Étienne', country: 'France' },
  '42100': { city: 'Saint-Étienne', country: 'France' },
  '21000': { city: 'Dijon', country: 'France' },
  '49000': { city: 'Angers', country: 'France' },
  '49100': { city: 'Angers', country: 'France' },
  '38000': { city: 'Grenoble', country: 'France' },
  '38100': { city: 'Grenoble', country: 'France' },
  '37000': { city: 'Tours', country: 'France' },
  '37100': { city: 'Tours', country: 'France' },
  '63000': { city: 'Clermont-Ferrand', country: 'France' },
  '63100': { city: 'Clermont-Ferrand', country: 'France' },
  '29200': { city: 'Brest', country: 'France' },
  '80000': { city: 'Amiens', country: 'France' },
  '87000': { city: 'Limoges', country: 'France' },
  '30000': { city: 'Nîmes', country: 'France' },
  '66000': { city: 'Perpignan', country: 'France' },
  '72000': { city: 'Le Mans', country: 'France' },
  '13100': { city: 'Aix-en-Provence', country: 'France' },
  '83000': { city: 'Toulon', country: 'France' },
  '57000': { city: 'Metz', country: 'France' },
  '54000': { city: 'Nancy', country: 'France' },
  '14000': { city: 'Caen', country: 'France' },
  '45000': { city: 'Orléans', country: 'France' },
  '68000': { city: 'Colmar', country: 'France' },
  '68100': { city: 'Mulhouse', country: 'France' },
  '97100': { city: 'Basse-Terre', country: 'France' },
  '97200': { city: 'Fort-de-France', country: 'France' },
  '97300': { city: 'Cayenne', country: 'France' },
  '97400': { city: 'Saint-Denis', country: 'France' },
  '97600': { city: 'Mamoudzou', country: 'France' },
  '92100': { city: 'Boulogne-Billancourt', country: 'France' },
  '92200': { city: 'Neuilly-sur-Seine', country: 'France' },
  '92300': { city: 'Levallois-Perret', country: 'France' },
  '92400': { city: 'Courbevoie', country: 'France' },
  '92500': { city: 'Rueil-Malmaison', country: 'France' },
  '92600': { city: 'Asnières-sur-Seine', country: 'France' },
  '92700': { city: 'Colombes', country: 'France' },
  '92800': { city: 'Puteaux', country: 'France' },
  '93100': { city: 'Montreuil', country: 'France' },
  '93200': { city: 'Saint-Denis', country: 'France' },
  '93300': { city: 'Aubervilliers', country: 'France' },
  '93400': { city: 'Saint-Ouen', country: 'France' },
  '93500': { city: 'Pantin', country: 'France' },
  '94100': { city: 'Saint-Maur-des-Fossés', country: 'France' },
  '94200': { city: 'Ivry-sur-Seine', country: 'France' },
  '94300': { city: 'Vincennes', country: 'France' },
  '94400': { city: 'Vitry-sur-Seine', country: 'France' },
  '94500': { city: 'Champigny-sur-Marne', country: 'France' },
  '95100': { city: 'Argenteuil', country: 'France' },
  '95200': { city: 'Sarcelles', country: 'France' },
  '95300': { city: 'Pontoise', country: 'France' },
  '78000': { city: 'Versailles', country: 'France' },
  '78100': { city: 'Saint-Germain-en-Laye', country: 'France' },
  '78200': { city: 'Mantes-la-Jolie', country: 'France' },
  '91000': { city: 'Évry', country: 'France' },
  '91100': { city: 'Corbeil-Essonnes', country: 'France' },
  '77000': { city: 'Melun', country: 'France' },
  '77100': { city: 'Meaux', country: 'France' },
};

const PREFIX_MAP: Record<string, { city: string; country: string }> = {
  '750': { city: 'Paris', country: 'France' },
  '130': { city: 'Marseille', country: 'France' },
  '690': { city: 'Lyon', country: 'France' },
  '310': { city: 'Toulouse', country: 'France' },
  '060': { city: 'Nice', country: 'France' },
  '440': { city: 'Nantes', country: 'France' },
  '340': { city: 'Montpellier', country: 'France' },
  '670': { city: 'Strasbourg', country: 'France' },
  '330': { city: 'Bordeaux', country: 'France' },
  '590': { city: 'Lille', country: 'France' },
  '350': { city: 'Rennes', country: 'France' },
  '380': { city: 'Grenoble', country: 'France' },
  '630': { city: 'Clermont-Ferrand', country: 'France' },
  '760': { city: 'Rouen', country: 'France' },
  '420': { city: 'Saint-Étienne', country: 'France' },
  '210': { city: 'Dijon', country: 'France' },
  '490': { city: 'Angers', country: 'France' },
  '370': { city: 'Tours', country: 'France' },
  '570': { city: 'Metz', country: 'France' },
  '540': { city: 'Nancy', country: 'France' },
  '140': { city: 'Caen', country: 'France' },
  '450': { city: 'Orléans', country: 'France' },
  '680': { city: 'Mulhouse / Colmar', country: 'France' },
  '920': { city: 'Hauts-de-Seine', country: 'France' },
  '930': { city: 'Seine-Saint-Denis', country: 'France' },
  '940': { city: 'Val-de-Marne', country: 'France' },
  '950': { city: 'Val-d\'Oise', country: 'France' },
  '780': { city: 'Yvelines', country: 'France' },
  '910': { city: 'Essonne', country: 'France' },
  '770': { city: 'Seine-et-Marne', country: 'France' },
};

export function lookupPostalCode(postalCode: string): { city: string; country: string } | null {
  const clean = postalCode.replace(/\s/g, '');
  if (clean.length < 3) return null;

  if (POSTAL_CODE_MAP[clean]) {
    return POSTAL_CODE_MAP[clean];
  }

  const prefix3 = clean.substring(0, 3);
  if (PREFIX_MAP[prefix3]) {
    return PREFIX_MAP[prefix3];
  }

  if (/^\d{5}$/.test(clean)) {
    return { city: '', country: 'France' };
  }

  return null;
}

export default POSTAL_CODE_MAP;
