/**
 * @fileoverview Styles for the Admin screen and its sub-components.
 */

import { StyleSheet } from 'react-native';

const adminStyles = StyleSheet.create({
  container: { flex: 1 },
  body: { flex: 1 },
  bodyContent: { padding: 24, gap: 20 },
  tabBarWrapper: { borderBottomWidth: 1, paddingHorizontal: 24 },
  tabBar: { flexDirection: 'row' as const, gap: 0 },
  tab: { flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 16, paddingVertical: 12, gap: 6, marginBottom: -1, borderBottomWidth: 2, borderBottomColor: 'transparent' },
  tabText: { fontSize: 14, fontWeight: '600' as const },
  sectionHeader: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, alignItems: 'center' as const },
  sectionTitle: { fontSize: 16, fontWeight: '600' as const },
  addBtn: { flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, gap: 6 },
  addBtnText: { color: '#FFF', fontSize: 13, fontWeight: '600' as const },
  usersList: { borderWidth: 1, borderRadius: 12, overflow: 'hidden' as const },
  userRow: { flexDirection: 'row' as const, alignItems: 'center' as const, paddingHorizontal: 20, paddingVertical: 14, gap: 12 },
  userAvatar: { width: 40, height: 40, borderRadius: 10, alignItems: 'center' as const, justifyContent: 'center' as const },
  userInitials: { fontSize: 14, fontWeight: '700' as const },
  userInfo: { flex: 1 },
  userName: { fontSize: 14, fontWeight: '600' as const },
  userEmail: { fontSize: 12, marginTop: 1 },
  roleBadge: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12 },
  roleText: { fontSize: 12, fontWeight: '600' as const },
  statusDot: { width: 8, height: 8, borderRadius: 4 },
  lastLogin: { fontSize: 12, minWidth: 80, textAlign: 'right' as const },
  emptyState: { borderWidth: 1, borderRadius: 12, padding: 40, alignItems: 'center' as const, gap: 8 },
  emptyTitle: { fontSize: 15, fontWeight: '600' as const },
  emptyDesc: { fontSize: 13 },
  subscriptionSection: { gap: 20 },
  currentPlan: { borderRadius: 12, padding: 24, position: 'relative' as const },
  planBadge: { position: 'absolute' as const, top: 12, right: 12, paddingHorizontal: 10, paddingVertical: 4, borderRadius: 6 },
  planBadgeText: { color: '#FFF', fontSize: 10, fontWeight: '700' as const, letterSpacing: 0.5 },
  planName: { fontSize: 28, fontWeight: '700' as const },
  planPrice: { fontSize: 36, fontWeight: '700' as const, marginTop: 4 },
  planPeriod: { fontSize: 16, fontWeight: '400' as const },
  planDesc: { fontSize: 14, marginTop: 8, lineHeight: 20 },
  planFeatures: { marginTop: 16, gap: 8 },
  planFeatureRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8 },
  planFeatureText: { fontSize: 14 },
  planFeatureTextSmall: { fontSize: 12 },
  plansGrid: { flexDirection: 'row' as const, gap: 16 },
  planCard: { flex: 1, borderWidth: 1, borderRadius: 12, padding: 20, gap: 6 },
  otherPlanName: { fontSize: 20, fontWeight: '700' as const },
  otherPlanPrice: { fontSize: 24, fontWeight: '700' as const },
  otherPlanDesc: { fontSize: 13, lineHeight: 18, marginBottom: 8 },
  changePlanBtn: { borderWidth: 1, borderRadius: 8, paddingVertical: 10, alignItems: 'center' as const, marginTop: 12 },
  changePlanBtnText: { fontSize: 14, fontWeight: '600' as const },
  usageSection: { gap: 16 },
  usageRow: { flexDirection: 'row' as const, gap: 12 },
  usageCard: { flex: 1, borderWidth: 1, borderRadius: 10, padding: 16 },
  usageLabel: { fontSize: 12, marginBottom: 4 },
  usageValue: { fontSize: 22, fontWeight: '700' as const },
  usageMax: { fontSize: 12, marginBottom: 10 },
  usageBarBg: { height: 6, borderRadius: 3 },
  usageBarFill: { height: 6, borderRadius: 3 },
  auditHeader: { gap: 8 },
  auditInfo: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, alignSelf: 'flex-start' as const },
  auditInfoText: { fontSize: 12, fontWeight: '500' as const },
  auditFilters: { flexGrow: 0 },
  filterChip: { paddingHorizontal: 16, paddingVertical: 8, borderRadius: 20, borderWidth: 1, marginRight: 8 },
  filterText: { fontSize: 13, fontWeight: '500' as const },
  auditList: { borderWidth: 1, borderRadius: 12, overflow: 'hidden' as const },
  auditRow: { flexDirection: 'row' as const, paddingHorizontal: 20, paddingVertical: 14, gap: 12 },
  auditIcon: { width: 36, height: 36, borderRadius: 8, alignItems: 'center' as const, justifyContent: 'center' as const, marginTop: 2 },
  auditContent: { flex: 1 },
  auditTopRow: { flexDirection: 'row' as const, alignItems: 'center' as const, gap: 6, flexWrap: 'wrap' as const, marginBottom: 4 },
  actionBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  actionBadgeText: { fontSize: 11, fontWeight: '600' as const },
  entityBadge: { paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6 },
  entityBadgeText: { fontSize: 11, fontWeight: '500' as const },
  auditEntity: { fontSize: 13, fontWeight: '600' as const },
  auditDetails: { fontSize: 12, lineHeight: 18, marginBottom: 4 },
  auditMeta: { flexDirection: 'row' as const, gap: 12 },
  auditUser: { fontSize: 11 },
  auditTime: { fontSize: 11 },
  inviteIconRow: { alignItems: 'center' as const, marginBottom: 4 },
  inviteIconCircle: { width: 56, height: 56, borderRadius: 28, alignItems: 'center' as const, justifyContent: 'center' as const },
  inviteRow: { flexDirection: 'row' as const, gap: 12 },
  inviteHalf: { flex: 1 },
  inviteNote: { flexDirection: 'row' as const, alignItems: 'flex-start' as const, gap: 8, padding: 12, borderRadius: 8 },
  inviteNoteText: { fontSize: 12, lineHeight: 18, flex: 1 },
});

export default adminStyles;
